### ISSUE TITLE
HTTP request failed! HTTP/1.1 429

### ISSUE THREAD

**Issue by cesarlwh** [vagalume/api-exemplos#19]
Estou tendo este erro ao fazer consultas:
HTTP request failed! HTTP/1.1 429

Estou usando PHP a URL fica assim:
https://api.vagalume.com.br/search.php?art=SPANDAU+BALLET&mus=TRUE

**Comment by AmarildoLima93** [comment]
Olá, Tudo bem ?

Nosso servidor retorna 429 quando existe muitas requisições no nosso servidor de um IP. Sendo assim, a ideia é você utilizar cache em suas requisições. Tentar padronizar a URL das buscas para melhorar o cache das consultas.

Qualquer dúvida, só avisar!
