### ISSUE TITLE
API Key

### ISSUE THREAD

**Issue by otaciliolacerda** [vagalume/api-exemplos#20]
No site diz que a partir do dia 23 será necessário o uso da API Key. Há exemplos de como deve ser feita a autenticação?

**Comment by AmarildoLima93** [comment]
Olá,

Estamos atualizando nossa documentação pra demonstrar as requisições com o uso da API Key. Basicamente, você precisa criar uma chave na URL: https://auth.vagalume.com.br/settings/api/ . Feito isso, você só precisar passar como parâmetro "apikey={key}" nas consultas da nossa API: http://api.vagalume.com.br/docs/.

Obrigado!
