### ISSUE TITLE
Erro de cabeçalho ao requisitar url de Imagens

### ISSUE THREAD

**Issue by DeniCarvalho** [vagalume/api-exemplos#25]
Inclusive o exemplo da documentação apresenta o mesmo erro.

```
// Exemplo de requisição
var artist = "3ade68b3gdb86eda3";
var song   = 10;
jQuery.getJSON(
    "https://api.vagalume.com.br/image.php"
        + "?bandID=" + artist
        + "&limit=" + limit,
        + "&apikey={key}"
    function (data) {
        // URL da imagem
        alert(data.images[0].url);
    }
);
```

**Comment by lafraia** [comment]
@DeniCarvalho Obrigado por reportar o erro. Já verificamos e está corrigido. Qualquer coisa, pode nos avisar neste ticket.

**Comment by DeniCarvalho** [comment]
@lafraia  Obrigado !
API disponibiliza alguma url com parâmetros capazes de retornar uma lista músicas juntamente com a url da imagem do respectivo artista? Por exemplo:
```
        $http.get('https://api.vagalume.com.br/search.excerpt?'
               + "q=" + q 
               + "&limit=" + limit 
               + "&apikey={key}").success(function (data, status, headers, config) {
               $scope.list = data.response.docs;         
        });
```
Aqui retornar o id do artista, teria então que fazer outra requisição para item... Isso é ruim.. 
Tem alguma forma de pegar a url da imagem nesta primeira consulta?

Agradeço.

**Comment by lafraia** [comment]
Infelizmente, não neste momento, mas você pode usar o padrão `profile.jpg` e `profile-big.jpg`, por exemplo:

https://s2.vagalume.com/u2/images/profile.jpg
https://s2.vagalume.com/u2/images/profile-big.jpg

É importante dizer que em todos os resultados de consultas na API do Vagalume você deve informar o usuário qual é a origem dos dados (no caso o Vagalume). http://api.vagalume.com.br/terms/

**Comment by DeniCarvalho** [comment]
@lafraia  Obrigado novamente.
Não sei se está questão será pública, mas uma dica pra quem for usar a url da imagem padrão.
Como nome do artista não segue um padrão quando introduzido na url, utilize o parâmetro de retorno "url" e o trate, exemplo:
```
            for (var i = 0; i < list.length; i++) {
                var artista = list[i].**url**.split("/");
                var urlImage = "https://s2.vagalume.com/" + artista[1] + "/images/profile.jpg";
            }
```

Estou ciente dos Termos.

**Comment by lafraia** [comment]
Obrigado @DeniCarvalho. Qualquer coisa é só falar.
