### ISSUE TITLE
Ionic Framework

### ISSUE THREAD

**Issue by tfaita** [vagalume/api-exemplos#26]
Tem algum exemplo em IONIC para consultar?

Abraços

**Comment by lafraia** [comment]
@tfaita Dê uma olhada no [Aplicativo para Rádios](https://github.com/vagalume/aplicativo-para-radios).

**Comment by tfaita** [comment]
Ok! Deu uma esclarecida! Consegui trazer a letra de uma musica.. Eu consigo buscar um aray listando todas as musicas de um determinado artista? Ou só se eu especificar qual musica? Qual Get q uso?
