### ISSUE TITLE
Busca não funciona

### ISSUE THREAD

**Issue by pedropamn** [vagalume/api-exemplos#27]
Olá

Aparentemente, a busca não está funcionando

Tentei na url: http://api.vagalume.com.br/search.excerpt?apikey=<API>&q=camarote&limit=5

Qualquer termo está gerando delay na consulta e retorna uma página em branco. Os exemplos também não estão funcionando.

Obrigado

**Comment by andersonajx** [comment]
Também estou passando pelo mesmo problema. Nenhuma das buscas https://api.vagalume.com.br/search.art, https://api.vagalume.com.br/search.excerpt, https://api.vagalume.com.br/search.artmus, https://api.vagalume.com.br/search.alb
estão funcionando.

**Comment by thadeudepaula** [comment]
Tivemos um problema no controle de acesso e resolvemos hoje pela manhã. Ao que parece todas as consultas estão funcionando normalmente.
