### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by jpsduarte** [vagalume/api-exemplos#30]
Timeout na consulta http://api.vagalume.com.br/search.artmus?apikey=660a4395f992ff67786584e238f501aa&q=Skank%20Vamos%20Fugir&limit=5

Essa consulta está no exemplo do site: 
http://api.vagalume.com.br/docs/search/#mus

**Comment by AmarildoLima93** [comment]
Olá, tudo bem ? 

O problema já foi resolvido, poderia testar novamente ?

Obrigado!
