### ISSUE TITLE
Service Unavailable - DNS failure

### ISSUE THREAD

**Issue by limagiran** [vagalume/api-exemplos#33]
Erro na consulta: http://api.vagalume.com.br/search.artmus?apikey=660a4395f992ff67786584e238f501aa&q=Skank%20Vamos%20Fugir&limit=5

------
Service Unavailable - DNS failure

The server is temporarily unable to service your request. Please try again later.
Reference # 11 . 2483d717.1497109231.7cf337c

**Comment by limagiran** [comment]
Resolvido.

**Comment by limagiran** [comment]
Vou reabrir pois está instável, às vezes funciona, às vezes não.
Outro exemplo: https://api.vagalume.com.br/search.excerpt?q=diante%20do%20Trono

**Comment by amarildolima** [comment]
Olá @limagiran,

Estamos trabalhando para resolver o problema, em breve vamos disponibilizar uma versão sem esse problema, eu avisarei aqui no ticket.

Obrigado pelo contato.

**Comment by amarildolima** [comment]
@limagiran Resolvemos o problema, pode testar novamente ?

Abraço,

**Comment by limagiran** [comment]
Testado e funcionando.
Obrigado!

**Comment by amarildolima** [comment]
Obrigado @limagiran.

Qualquer problema, avise!
