### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by guxxxta** [vagalume/api-exemplos#38]
Olá

Estou tendo dificuldades em realizar algumas consultas como no link abaixo:

http://api.vagalume.com.br/search.excerpt?apikey=660a4395f992ff67786584e238f501aa&q=vamos%20fugir&limit=5

O erro acontece mesmo utilizando uma key própria.

Alguma ideia?
Obrigado!

**Comment by guxxxta** [comment]
Serviço já normalizado.

**Comment by matmiranda** [comment]
Eu tenho o mesmo problema. Pode ver o que está acontecendo ?
