### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by matmiranda** [vagalume/api-exemplos#39]
Segue código do C#:

```
var apikey = "89d03117fe65f...";
var result_json =
await wc.DownloadStringTaskAsync($"https://api.vagalume.com.br/search.php?musid={value}&apikey={apikey}");
```

Funcionava normal, agora dá esse erro:

"O servidor remoto retornou um erro: (502) Gateway Incorreto."

**Comment by AmarildoLima93** [comment]
Olá @matmiranda, tudo bem ?

Você pode testar novamente ? Fizemos algumas modificações de perfomance na API.

Obrigado,

**Comment by matmiranda** [comment]
Aqui está normal, obrigado.

**Comment by AmarildoLima93** [comment]
Show!

Eu que agradeço. Qualquer problema, avise :) 

Abraço,
