### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by DanielRios549** [vagalume/api-exemplos#41]
Eu uso a API do Vagalume para pesquisar músicas na extensão do Spotify para o VS Code, e eu notei que nas primeiras requisições ele funciona normalmente, mas depois de algumas atualizadas na mesma URL, ele para de funcionar. O problema parece ser o arquivo favicon.ico, que está sendo chamado com o protocole http além do https, pelo menos é o aviso que retorna.

OBS: A página está escura por causa da extensão Dark Reader.

![screenshot from 2018-08-27 22-13-54](https://user-images.githubusercontent.com/11152535/44694901-ba9bb780-aa46-11e8-99eb-c7ce5fa77c6b.png)

**Comment by lafraia** [comment]
Olá @DanielRios549, este parece ser um problema no nosso servidor de API. Vamos verificar e retornar por aqui. Obrigado!

**Comment by paulobezerra** [comment]
Tenho um canal no Youtube e gostaria de utilizar a API do Vagalume como exemplo para um SPA utilizando VueJS, mas estou tendo esse problema do 502 Bad Gateway, alguma novidade quanto a essa issue?

**Comment by paulobezerra** [comment]
> Tenho um canal no Youtube e gostaria de utilizar a API do Vagalume como exemplo para um SPA utilizando VueJS, mas estou tendo esse problema do 502 Bad Gateway, alguma novidade quanto a essa issue?

Resolvi por hora (GAMBIARRA, kkkkk...) incluindo um atributo "hash" onde sempre uma string que gero de forma aleatória. Aparentemente o problema ocorre apenas ao acessar a mesma url repetidas vezes em um curto período de tempo.

**Comment by lafraia** [comment]
Caros, fizemos um pequeno ajuste na API que deve resolver o problema. Podem testar?

No longo prazo, ainda vamos verificar a viabilidade econômica de manter a API visto que, como falei anteriormente, nem todo mundo respeita os termos e não colocam os devidos créditos para o Vagalume.

Agradeço se puderem reavaliar suas interfaces e ver se estão de acordo com os termos de uso. Na prática, é muito importante colocar com evidência que os dados obtidos do Vagalume. Agradeço o contato e qualquer coisa favor abrir issues por aqui.
