### ISSUE TITLE
Direitos Autorais

### ISSUE THREAD

**Issue by tiagocedrim** [vagalume/api-exemplos#43]
```
A utilização da API do Vagalume não transfere os direito de uso das letras de músicas que devem ser adquiridas diretamente com os proprietários. Caso não queria obter os direitos de exibição da letra da música, utilize a API para obter apenas o link no Vagalume para que a letra seja exibida dentro do site do Vagalume.
```

Eu posso criar um aplicativo que mostra as letras das musicas colocando a logo do Vagalume? Ou para mostrar as letras das musicas eu preciso mostrar apenas um link para o site de vocês?

**Comment by tiagocedrim** [comment]
@lafraia Muito obrigado pela resposta.

Mesmo se eu colocar a letra, com a logo do Vagalume e com o link para a letra dentro do Vagalume ainda assim eu posso ter problemas? 

Caso eu tenha problema, então eu não posso mostrar a letra das musicas em nenhuma aplicação que eu quiser? 😢

**Comment by lafraia** [comment]
@tiagocedrim Acho que a melhor opção seria mostrar parte da letra e no final um link para ver a letra completa no Vagalume. Na prática, vc teria que pagar os direitos autorais para cada **exibição** da letra. É o que fazemos no site.

**Comment by tiagocedrim** [comment]
Existe algum plano pago no Vagalume para que eu possa mostrar toda a letra? @lafraia (desculpa por tanta pergunta)

**Comment by lafraia** [comment]
@tiagocedrim Na verdade, esta não é uma condição do Vagalume, mas sim como funciona o licenciamento de músicas no geral. Infelizmente, não depende de nós.

**Comment by tiagocedrim** [comment]
Muito obrigado @lafraia
