### ISSUE TITLE
Recebendo erro ao buscar musica pelo id

### ISSUE THREAD

**Issue by Natanielsr** [vagalume/api-exemplos#47]
aos vezes a resposta vem correta mas as vezes recebo o erro abaixo ao buscar pelo link
https://api.vagalume.com.br/search.php?apikey=1fb4de94d669a0d383dff71229eade60&musid=l3ade68b8g1d5d7fa

<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

**Comment by Natanielsr** [comment]
Troquei a api key e funcionou mas depois de um tempo volta a dar erro de novo

**Comment by lafraia** [comment]
@Natanielsr fizemos um pequeno ajuste na API que deve resolver o problema. Podem testar?

No longo prazo, ainda vamos verificar a viabilidade econômica de manter a API visto que, como falei anteriormente, nem todo mundo respeita os termos e não colocam os devidos créditos para o Vagalume.

Agradeço se puderem reavaliar suas interfaces e ver se estão de acordo com os termos de uso. Na prática, é muito importante colocar com evidência que os dados obtidos do Vagalume. Agradeço o contato e qualquer coisa favor abrir issues por aqui.
