### ISSUE TITLE
Discografia retornando erro 404

### ISSUE THREAD

**Issue by usernein** [vagalume/api-exemplos#48]
Qualquer tentativa de chamada à url de discografia está retornando 404 Not Found, seja o artista existente ou não. Não há erros na url. O próprio exempli documentado não está funcionando.

**Comment by lafraia** [comment]
Caros, fizemos um pequeno ajuste na API que deve resolver o problema. Podem testar?

No longo prazo, ainda vamos verificar a viabilidade econômica de manter a API visto que, como falei anteriormente, nem todo mundo respeita os termos e não colocam os devidos créditos para o Vagalume.

Agradeço se puderem reavaliar suas interfaces e ver se estão de acordo com os termos de uso. Na prática, é muito importante colocar com evidência que os dados obtidos do Vagalume. Agradeço o contato e qualquer coisa favor abrir issues por aqui.
