### ISSUE TITLE
Endpoint de busca por trecho parou de funcionar

### ISSUE THREAD

**Issue by fihawkins** [vagalume/api-exemplos#49]
https://api.vagalume.com.br/search.excerpt não está funcionando, somente com os exemplos da documentação. Se eu altero o parâmetro "q" ou coloco a minha APIKEY na URL, dá erro. Por exemplo:

http://api.vagalume.com.br/search.excerpt?apikey=660a4395f992ff67786584e238f501aa&q=vamos&limit=5

**Comment by usernein** [comment]
Hoje notei esse problema novamente

**Comment by lafraia** [comment]
Pessoal, vou verificar o problema.

De qualquer forma, gostaria de dizer que a API está com baixa prioridade no nosso pipeline pois a maioria das pessoas que a utilizam não colocam os devidos créditos para o Vagalume. Assim, acaba não agregando valor para a empresa. Estamos avaliando a viabilidade de continuar este projeto.

**Comment by lafraia** [comment]
Caros, fizemos um pequeno ajuste na API que deve resolver o problema. Podem testar?

No longo prazo, ainda vamos verificar a viabilidade econômica de manter a API visto que, como falei anteriormente, nem todo mundo respeita os termos e não colocam os devidos créditos para o Vagalume.

Agradeço se puderem reavaliar suas interfaces e ver se estão de acordo com os termos de uso. Na prática, é muito importante colocar com evidência que os dados obtidos do Vagalume. Agradeço o contato e qualquer coisa favor abrir issues por aqui.
