### ISSUE TITLE
"504 Gateway Time-out" ao realizar pesquisa

### ISSUE THREAD

**Issue by holyrics** [vagalume/api-exemplos#50]
Todas as pesquisas que retornam uma lista com resultado está dando o erro 504.
[https://api.vagalume.com.br/search.art?apikey=660a4395f992ff67786584e238f501aa&q=Skank&limit=5](https://api.vagalume.com.br/search.art?apikey=660a4395f992ff67786584e238f501aa&q=Skank&limit=5)

[https://api.vagalume.com.br/search.artmus?apikey=660a4395f992ff67786584e238f501aa&q=Skank%20Vamos%20Fugir&limit=5](https://api.vagalume.com.br/search.artmus?apikey=660a4395f992ff67786584e238f501aa&q=Skank%20Vamos%20Fugir&limit=5)

[https://api.vagalume.com.br/search.alb?apikey=660a4395f992ff67786584e238f501aa&q=U218%20Singles&limit=5](https://api.vagalume.com.br/search.alb?apikey=660a4395f992ff67786584e238f501aa&q=U218%20Singles&limit=5)

[https://api.vagalume.com.br/search.excerpt?apikey=660a4395f992ff67786584e238f501aa&q=vamos%20fugir&limit=5](https://api.vagalume.com.br/search.excerpt?apikey=660a4395f992ff67786584e238f501aa&q=vamos%20fugir&limit=5)
 
 
 
Porém o link que retorna uma música específica a partir do parâmetro **musid** está funcionando normalmente
[https://api.vagalume.com.br/search.php?apikey=660a4395f992ff67786584e238f501aa&musid=3ade68b6g4946fda3](https://api.vagalume.com.br/search.php?apikey=660a4395f992ff67786584e238f501aa&musid=3ade68b6g4946fda3)
 
 
PS: Links de exemplo retirados da documentação oficial

**Comment by cassioHilario** [comment]
Confirmo o chamada, estou tendo o mesmo problema

**Comment by lafraia** [comment]
Pessoal, vou verificar o problema.

De qualquer forma, gostaria de dizer que a API está com baixa prioridade no nosso pipeline pois a maioria das pessoas que a utilizam não colocam os devidos créditos para o Vagalume. Assim, acaba não agregando valor para a empresa. Estamos avaliando a viabilidade de continuar este projeto.

**Comment by holyrics** [comment]
Para registro:

A cada domingo, mais de 2 mil usuários diferentes realizam cerca de 9 mil pesquisas através da API.
A janela abaixo é exibida para todos os usuários.
E na parte superior direita é exibido o link para a música no site Vagalume, conforme a letra selecionada na lista da esquerda.
![web-search](https://user-images.githubusercontent.com/43863376/69071125-27162400-0a08-11ea-9883-9fade89d44ab.png)

Entendo perfeitamente o fato dessa funcionalidade não ter prioridade, principalmente por ser grátis.
O programa Holyrics também é grátis.
E agradeço pela ferramenta que disponibilizam, é bastante raro esse tipo de funcionalidade.
Se a intenção é realmente desativar o serviço, por favor, nos informe.
Pois dezenas de usuários entraram em contato conosco informando que não está funcionando, inclusive recebemos algumas avaliações negativas por isso.

Obs.: Percebemos também que muitos usuários deixam de utilizar esta funcionalidade no programa por não encontrar algumas músicas, principalmente as mais recentes.
Talvez isso pudesse ser melhorado se houvesse um filtro para gênero, por exemplo, pesquisar somente gospel. Mas não sei se é viável para vocês.

PS: Caso haja alguma possibilidade de parceria para utilização de API com servidor dedicado, favor entrar em contato conosco.

Obrigado!

**Comment by lafraia** [comment]
Caros, fizemos um pequeno ajuste na API que deve resolver o problema. Podem testar?

No longo prazo, ainda vamos verificar a viabilidade econômica de manter a API visto que, como falei anteriormente, nem todos respeitam os termos e não colocam os devidos créditos para o Vagalume.
