### ISSUE TITLE
Busca por termo não funciona

### ISSUE THREAD

**Issue by Keyne** [vagalume/api-exemplos#51]
https://api.vagalume.com.br/docs/search/
Links da documentação não funcionam mais.

**Comment by lafraia** [comment]
@Keyne fizemos um pequeno ajuste na API que deve resolver o problema. Podem testar?

No longo prazo, ainda vamos verificar a viabilidade econômica de manter a API visto que, como falei anteriormente, nem todo mundo respeita os termos e não colocam os devidos créditos para o Vagalume.

Agradeço se puderem reavaliar suas interfaces e ver se estão de acordo com os termos de uso. Na prática, é muito importante colocar com evidência que os dados obtidos do Vagalume. Agradeço o contato e qualquer coisa favor abrir issues por aqui.
