### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by amnubile** [vagalume/api-exemplos#55]
Hoje, durante o dia inteiro, está apresentando este erro "502 Bad Gateway" ao consultar a API.

**Comment by rpresb** [comment]
Os erros ainda persistem, as vezes recebo 504 e outras 502.

**Comment by lafraia** [comment]
Olá @amnubile e @rpresb. Desculpe, ma API deverá ser descontinuada muito em breve. Infelizmente, muita gente utiliza a API e não coloca os devidos créditos dos dados, assim, acaba não valendo a pena manter o serviço (que sempre foi gratuito).

**Comment by amnubile** [comment]
Boa Noite.

Esse serviço de API do Vagalume será mesmo descontinuado ?
Qual a previsão para ser desativado ?

Abraços.

Alexandre Manzo Nubile
11-9-8776-3374-TIM


Em seg., 5 de abr. de 2021 às 11:13, Daniel Lafraia <
***@***.***> escreveu:
