### ISSUE TITLE
503 Central de Ajuda

### ISSUE THREAD

**Issue by juanamm** [vagalume/api-exemplos#56]
Não consigo entrar na Central de Ajuda.
O link mudou?

![403-vagalume](https://user-images.githubusercontent.com/48572613/90999854-2a919980-e59e-11ea-9acb-915f600120e5.png)

**Comment by lafraia** [comment]
@juanamm O link é vagalume.zendesk.com, vou verificar os links para trocar nas páginas. Obrigado.
