### ISSUE TITLE
"Próxima página"

### ISSUE THREAD

**Issue by hms-douglas** [vagalume/api-exemplos#57]
Como eu faço para "ir para a próxima página"? A pesquisa retorna no máximo 10 resultados, como eu faço para retornar os 10 próximos resultados (por exemplo, do 11 ao 20)...

**Comment by lafraia** [comment]
@hms-douglas Desculpe, ma API deverá ser descontinuada muito em breve. Infelizmente, muita gente utiliza a API e não coloca os devidos créditos dos dados, assim, acaba não valendo a pena manter o serviço (que sempre foi gratuito).
