### ISSUE TITLE
API Discografias

### ISSUE THREAD

**Issue by guig3** [vagalume/api-exemplos#58]
A o link da **API Discografia Vagalume** não esta funcionando **ERRO 404**

DOCS: https://api.vagalume.com.br/docs/discografia/

**Comment by lafraia** [comment]
Olá @guig3. Desculpe, ma API deverá ser descontinuada muito em breve. Infelizmente, muita gente utiliza a API e não coloca os devidos créditos dos dados, assim, acaba não valendo a pena manter o serviço (que sempre foi gratuito).
